version: '3.8'

services:

  alpine:
    image: alpine:3.15.0
    command: ["/bin/sh", "-c", "sleep 3600"]

  nginx:
#    image: nginx:1.21.4-alpine
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
    - "80:8080"

  php:
#    image: php:8.1.1-fpm-alpine3.15
    build:
      context: ./php-fpm
      dockerfile: ./Dockerfile
    ports:
    - "9000:9000"