version: '3.3'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
    - "80:8080"

  php:
    build:
      context: ./php-fpm
      dockerfile: ./Dockerfile
    ports:
    - "9000:9000"